### PR TITLE
Bicop dist

### PR DESCRIPTION
**Pull request by tnagler**
To open the discussion:
- At some point, we should add the cdf, [but this needs to be done in cpp first](https://github.com/vinecopulib/vinecopulib/issues/168).
- I'm not super-happy with functions names like `hi1bicop()`. `bicop_hinv1()` would feel more natural, but maybe just because it's more similar to VineCopula (which is not a good reason obviously). Also other functions like par-to-tau conversion would get awkward with this notation

### CODE REVIEW

**Comment by tvatter** [comment]
- Concerning the CDF, agreed, I will try to do that ASAP.
- Concerning the function names, I think that they should all be part of `pbicop` with an additional character argument (e.g. `type`) taking either `"cdf"`, `"h"` or `"hinv"`. In my opinion, it would be more natural for R users and the documentation for bicop would include only the standard `d/p/q/r-bicop`.

**Comment by tnagler** [comment]
Sounds better than all this `h1` stuff etc. But does it makes sense to have `hinv` as part of `p-` which usually means "distribution function"?

**Comment by tvatter** [comment]
Maybe `hinv` should rather be part of `q-`.

Also, as discussed on Skype, in `bicop_dist.R`, I would replace `as.list(environment())` everywhere by `list(family = family, rotation = rotation, parameters = parameters)` in order to avoid copying the data.

**Comment by tnagler** [comment]
Just to clarify: `hinv` would be the only functionality of `q-` because there are no quantiles of bivariate distributions. Another option would be the way I did it in [kdecopula](https://tnagler.github.io/kdecopula/reference/hkdecop.html). There, I have one function `h-` with additional arguments `cond.var = 1/2` and `inverse = TRUE/FALSE`.

**Comment by tvatter** [comment]
Yes, it would be the only functionality of `q-`. 

If we go for your solution, I would call it `p-` instead of `h-` to avoid confusing people that are not familiar with the PCC literature.

**Comment by tnagler** [comment]
I don't think people not familiar with the PCC literature would want to use `h-` ;) In kdecopula it's also documented seperately from `p/d/r-`. I think `p-` would be even more confusing, since this is the unconditional cdf.

**Comment by tvatter** [comment]
OK, so let's keep `p-` for the distribution and `h-` for h-functions with additional arguments `cond_var = 1/2` and `inverse = TRUE/FALSE`.

**Comment by tvatter** [comment]
lines 98, `cond.var = 2` should be `cond_var = 2`

**Comment by laten21** [comment]
Hi, is there a package of multivariate kernel copula?

**Pull request merged**
