### PR TITLE
fix bugs in vine class generics (solves #128)

### PR DESCRIPTION
**Pull request by tnagler**
See #128. Proposed behavior:
```
> vc
3-dimensional vine distribution model ('vine_dist')
> summary(vc)
$margins
# A data.frame: 3 x 2 
  margin name
1      1 norm
2      2 norm
3      3 norm

$copula
# A data.frame: 3 x 9 
  tree edge conditioned conditioning family rotation parameters df  tau
1    1    1        3, 1                 bb1       90       3, 2  2 -0.8
2    1    2        2, 1                 bb1       90       3, 2  2 -0.8
3    2    1        3, 2            1    bb1       90       3, 2  2 -0.8

> 
> fit
3-dimensional vine distribution fit ('vine')
nobs = 50   logLik = -21.2   npars = 14.71   AIC = 71.83   BIC = 99.95   
> summary(fit)
$margins
# A data.frame: 3 x 6 
  margin name nobs   bw loglik d.f.
1      1   V1   50 0.63    -64  3.5
2      2   V2   50 0.58    -63  3.7
3      3   V3   50 0.51    -63  4.5

$copula
# A data.frame: 3 x 10 
  tree edge conditioned conditioning family rotation parameters df   tau loglik
1    1    1        2, 1               frank        0        -22  1 -0.83     62
2    1    2        1, 3              gumbel       90        5.3  1 -0.81     64
3    2    1        2, 3            1  frank        0        -14  1 -0.74     43

> 
> fit$names
[1] "V1" "V2" "V3"
> fit$copula$names
[1] "V1" "V2" "V3"
```

### CODE REVIEW

**Comment by tvatter** [comment]
- How about adding the variable names to the margins df?
- Isn't the `# A data.frame: ...` coming from printing the list of two data.frames a bit ugly? How about quickly writing a print method for this list too?
- It's internal, but for the naming, I would suggest that`margin_summary_vine_dist` becomes `get_vc_margins_summary`.
- Not a fan of `vc_model_df`. I would suggest `vinecop_summary_df`.
- In `print.vine_dist` and `print.vine`, isn't there a lot of copy-pasting from `print.vinecop_dist` and `print.vinecop` ? Also, is `!is.null(x$data)` still useful since we now save the log-likelihood?

**Comment by tnagler** [comment]
- The margins df does contain the variable names (column `name`) for class `vine`. It's a bit annoying that `name` is also used for `vine_dist`, but for the parametric family of the margins, for which `name` is not the most sensible argument name (rather `type` or `dist` or `family`).
- The `# A data.frame: ...` for each element of the list is on purpose. That way the output is still quite tidy and the structure is immediately clear. I doubt that telling "this is a list of to data frames which we will show now" makes things any easier.
- Agreed on `get_vc_margins_summary`
- Not sure about `vinecop_summary_df` since its also used for margins. `rvcl_summary_df`?
- Yes, `prints` can be modularized.
- Yes, the `!is.null(x$data)` can be removed.

**Comment by tvatter** [comment]
- Agreed, let's change the argument name then.
- Agreed.
- Nothing to add.
- How about simply `summary_df`?
- Nothing to add.
- Nothing to add.

**Comment by tnagler** [comment]
OK, I think I addressed everything.

**Pull request merged**
