### PR TITLE
U argument for simulation functions

### PR DESCRIPTION
**Pull request by tnagler**

### CODE REVIEW

**Comment by tvatter** [comment]
1. Shouldn't `prep_uniform_data` return `U`?
2. In the doc of `bicop_dist` and `vinecop_dist`, `U` does not need to be neither independent nor U(0,1), just in [0,1]. Additionally, I would write a bit more on the rosenblatt transform along the line of the doc in VineCopula.

**Comment by tnagler** [comment]
1. Yes, fixed.
2. I changed the description a bit. Which doc in VineCopula are you referring to? I don't see anything in `BiCopSim`, `RVineSim`.

**Comment by tvatter** [comment]
1. Perfect.
2. RVinePIT.

**Comment by tnagler** [comment]
2. Ah, OK. Don't you think it would be a bit weird to have this information with all the `bicop_dist`,  `dbicop` etc stuff? Maybe we should have a function for PITs as well and then link to this documentation.

**Comment by tvatter** [comment]
Yes, actually it's more for the vinecop that it's relevant IMO.

**Comment by tvatter** [comment]
See #43

**Pull request merged**
