### PR TITLE
Conversion between Kendall's tau and parameters

### PR DESCRIPTION
**Pull request by tnagler**

### CODE REVIEW

**Comment by tvatter** [comment]
What happens for e.g. 2-params families when using `tau_to_par`?

**Comment by tnagler** [comment]
Inherits the behavior from vinecopulib, i.e.
`std::runtime_error("Method not implemented for this family")`

**Comment by tnagler** [comment]
Maybe I should write a unit test for that.

**Comment by tvatter** [comment]
It's really neat! I didn't know it worked this nicely.

**Pull request merged**
