### PR TITLE
allow bicop_dist() with tll

### PR DESCRIPTION
**Pull request by tnagler**

### CODE REVIEW

**Comment by tvatter** [comment]
What's the usecase for this?

**Comment by tnagler** [comment]
Had someone thinking that `hbicop()` doesn't work with tll because the `hbicop(..., family = "tll", parameters = ..)` API doesn't, which is the part that is most prominently documented. I couldn't see much of a reason to disallow it.

**Comment by tvatter** [comment]
Got it. Yeah the usecase makes sense. The only thing that worries me is that the check of whether it's a copula is pretty mild no? But someone constructing manually a tll is likely a sufficiently savvy user.

**Comment by tnagler** [comment]
Yeah I kept it intentionally mild to minimize false positives. But if someone does something like 4 x copula density or  normal margins, it will detect it.

**Pull request merged**
